spring:
  datasource:
    url: jdbc:mysql://mysql_server:3306/plant_care?useSSL=false
    username: ${MY_SQL_USERNAME}
    password: ${MY_SQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

aws_access_key: ${AWS_ACCESS_KEY}
aws_secret_key: ${AWS_SECRET_ACCESS_KEY}

